services:
  django-website:
    build: 
      context: ./project
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn demo_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./project/:/project/
    # ports:
    #  - 8000:8000
    expose:
      - 8000
    env_file:
      - ./project/.env/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  # dns:
  #   build:
  #     context: ./dns/
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   command: named -c /etc/bind/named.conf -g -u named